/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.Point;
import javax.swing.JLabel;

/**
 *
 * @author Dericop
 */
public class SudokuGUI extends javax.swing.JFrame {
    public SudokuGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        sudokuContainer = new javax.swing.JPanel();
        s00 = new JLabel();
        s01 = new JLabel();
        s02 = new JLabel();
        s03 = new JLabel();
        s04 = new JLabel();
        s05 = new JLabel();
        s06 = new JLabel();
        s07 = new JLabel();
        s08 = new JLabel();
        s10 = new JLabel();
        s13 = new JLabel();
        s12 = new JLabel();
        s11 = new JLabel();
        s14 = new JLabel();
        s15 = new JLabel();
        s16 = new JLabel();
        s17 = new JLabel();
        s18 = new JLabel();
        s20 = new JLabel();
        s21 = new JLabel();
        s22 = new JLabel();
        s23 = new JLabel();
        s24 = new JLabel();
        s25 = new JLabel();
        s26 = new JLabel();
        s27 = new JLabel();
        s28 = new JLabel();
        s30 = new JLabel();
        s31 = new JLabel();
        s32 = new JLabel();
        s33 = new JLabel();
        s34 = new JLabel();
        s35 = new JLabel();
        s36 = new JLabel();
        s37 = new JLabel();
        s38 = new JLabel();
        s40 = new JLabel();
        s41 = new JLabel();
        s42 = new JLabel();
        s43 = new JLabel();
        s44 = new JLabel();
        s45 = new JLabel();
        s46 = new JLabel();
        s47 = new JLabel();
        s48 = new JLabel();
        s50 = new JLabel();
        s51 = new JLabel();
        s52 = new JLabel();
        s53 = new JLabel();
        s54 = new JLabel();
        s55 = new JLabel();
        s56 = new JLabel();
        s57 = new JLabel();
        s58 = new JLabel();
        s60 = new JLabel();
        s61 = new JLabel();
        s62 = new JLabel();
        s63 = new JLabel();
        s64 = new JLabel();
        s65 = new JLabel();
        s66 = new JLabel();
        s67 = new JLabel();
        s68 = new JLabel();
        s70 = new JLabel();
        s71 = new JLabel();
        s72 = new JLabel();
        s73 = new JLabel();
        s74 = new JLabel();
        s75 = new JLabel();
        s76 = new JLabel();
        s77 = new JLabel();
        s78 = new JLabel();
        s80 = new JLabel();
        s81 = new JLabel();
        s82 = new JLabel();
        s83 = new JLabel();
        s84 = new JLabel();
        s85 = new JLabel();
        s86 = new JLabel();
        s87 = new JLabel();
        s88 = new JLabel();
        execute = new javax.swing.JButton();
        txtConsole = new JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        log = new javax.swing.JTextArea();
        txt_console1 = new JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new Color(51, 51, 51));

        sudokuContainer.setBackground(new Color(51, 51, 51));

        s00.setBackground(new Color(51, 51, 51));
        s00.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s00.setForeground(new Color(255, 255, 255));
        s00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s00.setText("0");
        s00.setToolTipText("");
        s00.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s00.setOpaque(true);
        s00.setPreferredSize(new java.awt.Dimension(50, 50));

        s01.setBackground(new Color(51, 51, 51));
        s01.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s01.setForeground(new Color(255, 255, 255));
        s01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s01.setText("0");
        s01.setToolTipText("");
        s01.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s01.setOpaque(true);
        s01.setPreferredSize(new java.awt.Dimension(50, 50));

        s02.setBackground(new Color(51, 51, 51));
        s02.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s02.setForeground(new Color(255, 255, 255));
        s02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s02.setText("0");
        s02.setToolTipText("");
        s02.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s02.setOpaque(true);
        s02.setPreferredSize(new java.awt.Dimension(50, 50));

        s03.setBackground(new Color(51, 51, 51));
        s03.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s03.setForeground(new Color(255, 255, 255));
        s03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s03.setText("0");
        s03.setToolTipText("");
        s03.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s03.setOpaque(true);
        s03.setPreferredSize(new java.awt.Dimension(50, 50));

        s04.setBackground(new Color(51, 51, 51));
        s04.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s04.setForeground(new Color(255, 255, 255));
        s04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s04.setText("0");
        s04.setToolTipText("");
        s04.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s04.setOpaque(true);
        s04.setPreferredSize(new java.awt.Dimension(50, 50));

        s05.setBackground(new Color(51, 51, 51));
        s05.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s05.setForeground(new Color(255, 255, 255));
        s05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s05.setText("0");
        s05.setToolTipText("");
        s05.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s05.setOpaque(true);
        s05.setPreferredSize(new java.awt.Dimension(50, 50));

        s06.setBackground(new Color(51, 51, 51));
        s06.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s06.setForeground(new Color(255, 255, 255));
        s06.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s06.setText("0");
        s06.setToolTipText("");
        s06.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s06.setOpaque(true);
        s06.setPreferredSize(new java.awt.Dimension(50, 50));

        s07.setBackground(new Color(51, 51, 51));
        s07.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s07.setForeground(new Color(255, 255, 255));
        s07.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s07.setText("0");
        s07.setToolTipText("");
        s07.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s07.setOpaque(true);
        s07.setPreferredSize(new java.awt.Dimension(50, 50));

        s08.setBackground(new Color(51, 51, 51));
        s08.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s08.setForeground(new Color(255, 255, 255));
        s08.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s08.setText("0");
        s08.setToolTipText("");
        s08.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s08.setOpaque(true);
        s08.setPreferredSize(new java.awt.Dimension(50, 50));

        s10.setBackground(new Color(51, 51, 51));
        s10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s10.setForeground(new Color(255, 255, 255));
        s10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s10.setText("0");
        s10.setToolTipText("");
        s10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s10.setOpaque(true);
        s10.setPreferredSize(new java.awt.Dimension(50, 50));

        s13.setBackground(new Color(51, 51, 51));
        s13.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s13.setForeground(new Color(255, 255, 255));
        s13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s13.setText("0");
        s13.setToolTipText("");
        s13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s13.setOpaque(true);
        s13.setPreferredSize(new java.awt.Dimension(50, 50));

        s12.setBackground(new Color(51, 51, 51));
        s12.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s12.setForeground(new Color(255, 255, 255));
        s12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s12.setText("0");
        s12.setToolTipText("");
        s12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s12.setOpaque(true);
        s12.setPreferredSize(new java.awt.Dimension(50, 50));

        s11.setBackground(new Color(51, 51, 51));
        s11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s11.setForeground(new Color(255, 255, 255));
        s11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s11.setText("0");
        s11.setToolTipText("");
        s11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s11.setOpaque(true);
        s11.setPreferredSize(new java.awt.Dimension(50, 50));

        s14.setBackground(new Color(51, 51, 51));
        s14.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s14.setForeground(new Color(255, 255, 255));
        s14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s14.setText("0");
        s14.setToolTipText("");
        s14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s14.setOpaque(true);
        s14.setPreferredSize(new java.awt.Dimension(50, 50));

        s15.setBackground(new Color(51, 51, 51));
        s15.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s15.setForeground(new Color(255, 255, 255));
        s15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s15.setText("0");
        s15.setToolTipText("");
        s15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s15.setOpaque(true);
        s15.setPreferredSize(new java.awt.Dimension(50, 50));

        s16.setBackground(new Color(51, 51, 51));
        s16.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s16.setForeground(new Color(255, 255, 255));
        s16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s16.setText("0");
        s16.setToolTipText("");
        s16.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s16.setOpaque(true);
        s16.setPreferredSize(new java.awt.Dimension(50, 50));

        s17.setBackground(new Color(51, 51, 51));
        s17.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s17.setForeground(new Color(255, 255, 255));
        s17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s17.setText("0");
        s17.setToolTipText("");
        s17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s17.setOpaque(true);
        s17.setPreferredSize(new java.awt.Dimension(50, 50));

        s18.setBackground(new Color(51, 51, 51));
        s18.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s18.setForeground(new Color(255, 255, 255));
        s18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s18.setText("0");
        s18.setToolTipText("");
        s18.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s18.setOpaque(true);
        s18.setPreferredSize(new java.awt.Dimension(50, 50));

        s20.setBackground(new Color(51, 51, 51));
        s20.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s20.setForeground(new Color(255, 255, 255));
        s20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s20.setText("0");
        s20.setToolTipText("");
        s20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s20.setOpaque(true);
        s20.setPreferredSize(new java.awt.Dimension(50, 50));

        s21.setBackground(new Color(51, 51, 51));
        s21.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s21.setForeground(new Color(255, 255, 255));
        s21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s21.setText("0");
        s21.setToolTipText("");
        s21.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s21.setOpaque(true);
        s21.setPreferredSize(new java.awt.Dimension(50, 50));

        s22.setBackground(new Color(51, 51, 51));
        s22.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s22.setForeground(new Color(255, 255, 255));
        s22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s22.setText("0");
        s22.setToolTipText("");
        s22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s22.setOpaque(true);
        s22.setPreferredSize(new java.awt.Dimension(50, 50));

        s23.setBackground(new Color(51, 51, 51));
        s23.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s23.setForeground(new Color(255, 255, 255));
        s23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s23.setText("0");
        s23.setToolTipText("");
        s23.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s23.setOpaque(true);
        s23.setPreferredSize(new java.awt.Dimension(50, 50));

        s24.setBackground(new Color(51, 51, 51));
        s24.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s24.setForeground(new Color(255, 255, 255));
        s24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s24.setText("0");
        s24.setToolTipText("");
        s24.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s24.setOpaque(true);
        s24.setPreferredSize(new java.awt.Dimension(50, 50));

        s25.setBackground(new Color(51, 51, 51));
        s25.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s25.setForeground(new Color(255, 255, 255));
        s25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s25.setText("0");
        s25.setToolTipText("");
        s25.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s25.setOpaque(true);
        s25.setPreferredSize(new java.awt.Dimension(50, 50));

        s26.setBackground(new Color(51, 51, 51));
        s26.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s26.setForeground(new Color(255, 255, 255));
        s26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s26.setText("0");
        s26.setToolTipText("");
        s26.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s26.setOpaque(true);
        s26.setPreferredSize(new java.awt.Dimension(50, 50));

        s27.setBackground(new Color(51, 51, 51));
        s27.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s27.setForeground(new Color(255, 255, 255));
        s27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s27.setText("0");
        s27.setToolTipText("");
        s27.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s27.setOpaque(true);
        s27.setPreferredSize(new java.awt.Dimension(50, 50));

        s28.setBackground(new Color(51, 51, 51));
        s28.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s28.setForeground(new Color(255, 255, 255));
        s28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s28.setText("0");
        s28.setToolTipText("");
        s28.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s28.setOpaque(true);
        s28.setPreferredSize(new java.awt.Dimension(50, 50));

        s30.setBackground(new Color(51, 51, 51));
        s30.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s30.setForeground(new Color(255, 255, 255));
        s30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s30.setText("0");
        s30.setToolTipText("");
        s30.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s30.setOpaque(true);
        s30.setPreferredSize(new java.awt.Dimension(50, 50));

        s31.setBackground(new Color(51, 51, 51));
        s31.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s31.setForeground(new Color(255, 255, 255));
        s31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s31.setText("0");
        s31.setToolTipText("");
        s31.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s31.setOpaque(true);
        s31.setPreferredSize(new java.awt.Dimension(50, 50));

        s32.setBackground(new Color(51, 51, 51));
        s32.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s32.setForeground(new Color(255, 255, 255));
        s32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s32.setText("0");
        s32.setToolTipText("");
        s32.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s32.setOpaque(true);
        s32.setPreferredSize(new java.awt.Dimension(50, 50));

        s33.setBackground(new Color(51, 51, 51));
        s33.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s33.setForeground(new Color(255, 255, 255));
        s33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s33.setText("0");
        s33.setToolTipText("");
        s33.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s33.setOpaque(true);
        s33.setPreferredSize(new java.awt.Dimension(50, 50));

        s34.setBackground(new Color(51, 51, 51));
        s34.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s34.setForeground(new Color(255, 255, 255));
        s34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s34.setText("0");
        s34.setToolTipText("");
        s34.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s34.setOpaque(true);
        s34.setPreferredSize(new java.awt.Dimension(50, 50));

        s35.setBackground(new Color(51, 51, 51));
        s35.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s35.setForeground(new Color(255, 255, 255));
        s35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s35.setText("0");
        s35.setToolTipText("");
        s35.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s35.setOpaque(true);
        s35.setPreferredSize(new java.awt.Dimension(50, 50));

        s36.setBackground(new Color(51, 51, 51));
        s36.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s36.setForeground(new Color(255, 255, 255));
        s36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s36.setText("0");
        s36.setToolTipText("");
        s36.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s36.setOpaque(true);
        s36.setPreferredSize(new java.awt.Dimension(50, 50));

        s37.setBackground(new Color(51, 51, 51));
        s37.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s37.setForeground(new Color(255, 255, 255));
        s37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s37.setText("0");
        s37.setToolTipText("");
        s37.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s37.setOpaque(true);
        s37.setPreferredSize(new java.awt.Dimension(50, 50));

        s38.setBackground(new Color(51, 51, 51));
        s38.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s38.setForeground(new Color(255, 255, 255));
        s38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s38.setText("0");
        s38.setToolTipText("");
        s38.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s38.setOpaque(true);
        s38.setPreferredSize(new java.awt.Dimension(50, 50));

        s40.setBackground(new Color(51, 51, 51));
        s40.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s40.setForeground(new Color(255, 255, 255));
        s40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s40.setText("0");
        s40.setToolTipText("");
        s40.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s40.setOpaque(true);
        s40.setPreferredSize(new java.awt.Dimension(50, 50));

        s41.setBackground(new Color(51, 51, 51));
        s41.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s41.setForeground(new Color(255, 255, 255));
        s41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s41.setText("0");
        s41.setToolTipText("");
        s41.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s41.setOpaque(true);
        s41.setPreferredSize(new java.awt.Dimension(50, 50));

        s42.setBackground(new Color(51, 51, 51));
        s42.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s42.setForeground(new Color(255, 255, 255));
        s42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s42.setText("0");
        s42.setToolTipText("");
        s42.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s42.setOpaque(true);
        s42.setPreferredSize(new java.awt.Dimension(50, 50));

        s43.setBackground(new Color(51, 51, 51));
        s43.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s43.setForeground(new Color(255, 255, 255));
        s43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s43.setText("0");
        s43.setToolTipText("");
        s43.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s43.setOpaque(true);
        s43.setPreferredSize(new java.awt.Dimension(50, 50));

        s44.setBackground(new Color(51, 51, 51));
        s44.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s44.setForeground(new Color(255, 255, 255));
        s44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s44.setText("0");
        s44.setToolTipText("");
        s44.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s44.setOpaque(true);
        s44.setPreferredSize(new java.awt.Dimension(50, 50));

        s45.setBackground(new Color(51, 51, 51));
        s45.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s45.setForeground(new Color(255, 255, 255));
        s45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s45.setText("0");
        s45.setToolTipText("");
        s45.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s45.setOpaque(true);
        s45.setPreferredSize(new java.awt.Dimension(50, 50));

        s46.setBackground(new Color(51, 51, 51));
        s46.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s46.setForeground(new Color(255, 255, 255));
        s46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s46.setText("0");
        s46.setToolTipText("");
        s46.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s46.setOpaque(true);
        s46.setPreferredSize(new java.awt.Dimension(50, 50));

        s47.setBackground(new Color(51, 51, 51));
        s47.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s47.setForeground(new Color(255, 255, 255));
        s47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s47.setText("0");
        s47.setToolTipText("");
        s47.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s47.setOpaque(true);
        s47.setPreferredSize(new java.awt.Dimension(50, 50));

        s48.setBackground(new Color(51, 51, 51));
        s48.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s48.setForeground(new Color(255, 255, 255));
        s48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s48.setText("0");
        s48.setToolTipText("");
        s48.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s48.setOpaque(true);
        s48.setPreferredSize(new java.awt.Dimension(50, 50));

        s50.setBackground(new Color(51, 51, 51));
        s50.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s50.setForeground(new Color(255, 255, 255));
        s50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s50.setText("0");
        s50.setToolTipText("");
        s50.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s50.setOpaque(true);
        s50.setPreferredSize(new java.awt.Dimension(50, 50));

        s51.setBackground(new Color(51, 51, 51));
        s51.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s51.setForeground(new Color(255, 255, 255));
        s51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s51.setText("0");
        s51.setToolTipText("");
        s51.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s51.setOpaque(true);
        s51.setPreferredSize(new java.awt.Dimension(50, 50));

        s52.setBackground(new Color(51, 51, 51));
        s52.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s52.setForeground(new Color(255, 255, 255));
        s52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s52.setText("0");
        s52.setToolTipText("");
        s52.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s52.setOpaque(true);
        s52.setPreferredSize(new java.awt.Dimension(50, 50));

        s53.setBackground(new Color(51, 51, 51));
        s53.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s53.setForeground(new Color(255, 255, 255));
        s53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s53.setText("0");
        s53.setToolTipText("");
        s53.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s53.setOpaque(true);
        s53.setPreferredSize(new java.awt.Dimension(50, 50));

        s54.setBackground(new Color(51, 51, 51));
        s54.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s54.setForeground(new Color(255, 255, 255));
        s54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s54.setText("0");
        s54.setToolTipText("");
        s54.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s54.setOpaque(true);
        s54.setPreferredSize(new java.awt.Dimension(50, 50));

        s55.setBackground(new Color(51, 51, 51));
        s55.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s55.setForeground(new Color(255, 255, 255));
        s55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s55.setText("0");
        s55.setToolTipText("");
        s55.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s55.setOpaque(true);
        s55.setPreferredSize(new java.awt.Dimension(50, 50));

        s56.setBackground(new Color(51, 51, 51));
        s56.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s56.setForeground(new Color(255, 255, 255));
        s56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s56.setText("0");
        s56.setToolTipText("");
        s56.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s56.setOpaque(true);
        s56.setPreferredSize(new java.awt.Dimension(50, 50));

        s57.setBackground(new Color(51, 51, 51));
        s57.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s57.setForeground(new Color(255, 255, 255));
        s57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s57.setText("0");
        s57.setToolTipText("");
        s57.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s57.setOpaque(true);
        s57.setPreferredSize(new java.awt.Dimension(50, 50));

        s58.setBackground(new Color(51, 51, 51));
        s58.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s58.setForeground(new Color(255, 255, 255));
        s58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s58.setText("0");
        s58.setToolTipText("");
        s58.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s58.setOpaque(true);
        s58.setPreferredSize(new java.awt.Dimension(50, 50));

        s60.setBackground(new Color(51, 51, 51));
        s60.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s60.setForeground(new Color(255, 255, 255));
        s60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s60.setText("0");
        s60.setToolTipText("");
        s60.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s60.setOpaque(true);
        s60.setPreferredSize(new java.awt.Dimension(50, 50));

        s61.setBackground(new Color(51, 51, 51));
        s61.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s61.setForeground(new Color(255, 255, 255));
        s61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s61.setText("0");
        s61.setToolTipText("");
        s61.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s61.setOpaque(true);
        s61.setPreferredSize(new java.awt.Dimension(50, 50));

        s62.setBackground(new Color(51, 51, 51));
        s62.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s62.setForeground(new Color(255, 255, 255));
        s62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s62.setText("0");
        s62.setToolTipText("");
        s62.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s62.setOpaque(true);
        s62.setPreferredSize(new java.awt.Dimension(50, 50));

        s63.setBackground(new Color(51, 51, 51));
        s63.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s63.setForeground(new Color(255, 255, 255));
        s63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s63.setText("0");
        s63.setToolTipText("");
        s63.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s63.setOpaque(true);
        s63.setPreferredSize(new java.awt.Dimension(50, 50));

        s64.setBackground(new Color(51, 51, 51));
        s64.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s64.setForeground(new Color(255, 255, 255));
        s64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s64.setText("0");
        s64.setToolTipText("");
        s64.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s64.setOpaque(true);
        s64.setPreferredSize(new java.awt.Dimension(50, 50));

        s65.setBackground(new Color(51, 51, 51));
        s65.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s65.setForeground(new Color(255, 255, 255));
        s65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s65.setText("0");
        s65.setToolTipText("");
        s65.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s65.setOpaque(true);
        s65.setPreferredSize(new java.awt.Dimension(50, 50));

        s66.setBackground(new Color(51, 51, 51));
        s66.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s66.setForeground(new Color(255, 255, 255));
        s66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s66.setText("0");
        s66.setToolTipText("");
        s66.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s66.setOpaque(true);
        s66.setPreferredSize(new java.awt.Dimension(50, 50));

        s67.setBackground(new Color(51, 51, 51));
        s67.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s67.setForeground(new Color(255, 255, 255));
        s67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s67.setText("0");
        s67.setToolTipText("");
        s67.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s67.setOpaque(true);
        s67.setPreferredSize(new java.awt.Dimension(50, 50));

        s68.setBackground(new Color(51, 51, 51));
        s68.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s68.setForeground(new Color(255, 255, 255));
        s68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s68.setText("0");
        s68.setToolTipText("");
        s68.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s68.setOpaque(true);
        s68.setPreferredSize(new java.awt.Dimension(50, 50));

        s70.setBackground(new Color(51, 51, 51));
        s70.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s70.setForeground(new Color(255, 255, 255));
        s70.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s70.setText("0");
        s70.setToolTipText("");
        s70.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s70.setOpaque(true);
        s70.setPreferredSize(new java.awt.Dimension(50, 50));

        s71.setBackground(new Color(51, 51, 51));
        s71.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s71.setForeground(new Color(255, 255, 255));
        s71.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s71.setText("0");
        s71.setToolTipText("");
        s71.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s71.setOpaque(true);
        s71.setPreferredSize(new java.awt.Dimension(50, 50));

        s72.setBackground(new Color(51, 51, 51));
        s72.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s72.setForeground(new Color(255, 255, 255));
        s72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s72.setText("0");
        s72.setToolTipText("");
        s72.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s72.setOpaque(true);
        s72.setPreferredSize(new java.awt.Dimension(50, 50));

        s73.setBackground(new Color(51, 51, 51));
        s73.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s73.setForeground(new Color(255, 255, 255));
        s73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s73.setText("0");
        s73.setToolTipText("");
        s73.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s73.setOpaque(true);
        s73.setPreferredSize(new java.awt.Dimension(50, 50));

        s74.setBackground(new Color(51, 51, 51));
        s74.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s74.setForeground(new Color(255, 255, 255));
        s74.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s74.setText("0");
        s74.setToolTipText("");
        s74.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s74.setOpaque(true);
        s74.setPreferredSize(new java.awt.Dimension(50, 50));

        s75.setBackground(new Color(51, 51, 51));
        s75.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s75.setForeground(new Color(255, 255, 255));
        s75.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s75.setText("0");
        s75.setToolTipText("");
        s75.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s75.setOpaque(true);
        s75.setPreferredSize(new java.awt.Dimension(50, 50));

        s76.setBackground(new Color(51, 51, 51));
        s76.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s76.setForeground(new Color(255, 255, 255));
        s76.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s76.setText("0");
        s76.setToolTipText("");
        s76.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s76.setOpaque(true);
        s76.setPreferredSize(new java.awt.Dimension(50, 50));

        s77.setBackground(new Color(51, 51, 51));
        s77.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s77.setForeground(new Color(255, 255, 255));
        s77.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s77.setText("0");
        s77.setToolTipText("");
        s77.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s77.setOpaque(true);
        s77.setPreferredSize(new java.awt.Dimension(50, 50));

        s78.setBackground(new Color(51, 51, 51));
        s78.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s78.setForeground(new Color(255, 255, 255));
        s78.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s78.setText("0");
        s78.setToolTipText("");
        s78.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s78.setOpaque(true);
        s78.setPreferredSize(new java.awt.Dimension(50, 50));

        s80.setBackground(new Color(51, 51, 51));
        s80.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s80.setForeground(new Color(255, 255, 255));
        s80.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s80.setText("0");
        s80.setToolTipText("");
        s80.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s80.setOpaque(true);
        s80.setPreferredSize(new java.awt.Dimension(50, 50));

        s81.setBackground(new Color(51, 51, 51));
        s81.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s81.setForeground(new Color(255, 255, 255));
        s81.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s81.setText("0");
        s81.setToolTipText("");
        s81.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s81.setOpaque(true);
        s81.setPreferredSize(new java.awt.Dimension(50, 50));

        s82.setBackground(new Color(51, 51, 51));
        s82.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s82.setForeground(new Color(255, 255, 255));
        s82.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s82.setText("0");
        s82.setToolTipText("");
        s82.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s82.setOpaque(true);
        s82.setPreferredSize(new java.awt.Dimension(50, 50));

        s83.setBackground(new Color(51, 51, 51));
        s83.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s83.setForeground(new Color(255, 255, 255));
        s83.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s83.setText("0");
        s83.setToolTipText("");
        s83.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s83.setOpaque(true);
        s83.setPreferredSize(new java.awt.Dimension(50, 50));

        s84.setBackground(new Color(51, 51, 51));
        s84.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s84.setForeground(new Color(255, 255, 255));
        s84.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s84.setText("0");
        s84.setToolTipText("");
        s84.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s84.setOpaque(true);
        s84.setPreferredSize(new java.awt.Dimension(50, 50));

        s85.setBackground(new Color(51, 51, 51));
        s85.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s85.setForeground(new Color(255, 255, 255));
        s85.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s85.setText("0");
        s85.setToolTipText("");
        s85.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s85.setOpaque(true);
        s85.setPreferredSize(new java.awt.Dimension(50, 50));

        s86.setBackground(new Color(51, 51, 51));
        s86.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s86.setForeground(new Color(255, 255, 255));
        s86.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s86.setText("0");
        s86.setToolTipText("");
        s86.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s86.setOpaque(true);
        s86.setPreferredSize(new java.awt.Dimension(50, 50));

        s87.setBackground(new Color(51, 51, 51));
        s87.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s87.setForeground(new Color(255, 255, 255));
        s87.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s87.setText("0");
        s87.setToolTipText("");
        s87.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s87.setOpaque(true);
        s87.setPreferredSize(new java.awt.Dimension(50, 50));

        s88.setBackground(new Color(51, 51, 51));
        s88.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s88.setForeground(new Color(255, 255, 255));
        s88.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s88.setText("0");
        s88.setToolTipText("");
        s88.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.lightGray, Color.lightGray, Color.white, Color.white));
        s88.setOpaque(true);
        s88.setPreferredSize(new java.awt.Dimension(50, 50));

        execute.setBackground(new Color(51, 51, 51));
        execute.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        execute.setForeground(new Color(255, 255, 255));
        execute.setText("Resolver");
        execute.setFocusable(false);

        javax.swing.GroupLayout sudokuContainerLayout = new javax.swing.GroupLayout(sudokuContainer);
        sudokuContainer.setLayout(sudokuContainerLayout);
        sudokuContainerLayout.setHorizontalGroup(
            sudokuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sudokuContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sudokuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sudokuContainerLayout.createSequentialGroup()
                        .addComponent(s00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sudokuContainerLayout.createSequentialGroup()
                        .addComponent(s10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sudokuContainerLayout.createSequentialGroup()
                        .addComponent(s20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sudokuContainerLayout.createSequentialGroup()
                        .addComponent(s30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sudokuContainerLayout.createSequentialGroup()
                        .addComponent(s40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sudokuContainerLayout.createSequentialGroup()
                        .addComponent(s50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sudokuContainerLayout.createSequentialGroup()
                        .addComponent(s60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s67, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s68, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sudokuContainerLayout.createSequentialGroup()
                        .addGroup(sudokuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, sudokuContainerLayout.createSequentialGroup()
                                .addComponent(s80, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(s81, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(s82, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, sudokuContainerLayout.createSequentialGroup()
                                .addComponent(s70, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(s71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(s72, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sudokuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sudokuContainerLayout.createSequentialGroup()
                                .addComponent(s73, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(s74, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(s75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(s76, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(s77, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(s78, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sudokuContainerLayout.createSequentialGroup()
                                .addComponent(s83, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(s84, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(s85, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(s86, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(s87, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(s88, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(execute, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        sudokuContainerLayout.setVerticalGroup(
            sudokuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sudokuContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sudokuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sudokuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sudokuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sudokuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sudokuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sudokuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sudokuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s67, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s68, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sudokuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s70, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s72, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s73, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s74, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s76, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s77, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s78, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sudokuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s80, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s81, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s82, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s83, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s84, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s85, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s86, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s87, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s88, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(execute, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
        );

        s00.getAccessibleContext().setAccessibleName("s00");
        s01.getAccessibleContext().setAccessibleName("s01");
        s02.getAccessibleContext().setAccessibleName("s02");
        s03.getAccessibleContext().setAccessibleName("s03");
        s04.getAccessibleContext().setAccessibleName("s04");
        s05.getAccessibleContext().setAccessibleName("s05");
        s06.getAccessibleContext().setAccessibleName("s06");
        s07.getAccessibleContext().setAccessibleName("s07");
        s08.getAccessibleContext().setAccessibleName("s08");
        s10.getAccessibleContext().setAccessibleName("s10");
        s13.getAccessibleContext().setAccessibleName("s13");
        s12.getAccessibleContext().setAccessibleName("s12");
        s11.getAccessibleContext().setAccessibleName("s11");
        s14.getAccessibleContext().setAccessibleName("s14");
        s15.getAccessibleContext().setAccessibleName("s15");
        s16.getAccessibleContext().setAccessibleName("s16");
        s17.getAccessibleContext().setAccessibleName("s17");
        s18.getAccessibleContext().setAccessibleName("s18");
        s20.getAccessibleContext().setAccessibleName("s20");
        s21.getAccessibleContext().setAccessibleName("s21");
        s22.getAccessibleContext().setAccessibleName("s22");
        s23.getAccessibleContext().setAccessibleName("s23");
        s24.getAccessibleContext().setAccessibleName("s24");
        s25.getAccessibleContext().setAccessibleName("s25");
        s26.getAccessibleContext().setAccessibleName("s26");
        s27.getAccessibleContext().setAccessibleName("s27");
        s28.getAccessibleContext().setAccessibleName("s28");
        s30.getAccessibleContext().setAccessibleName("s30");
        s31.getAccessibleContext().setAccessibleName("s31");
        s32.getAccessibleContext().setAccessibleName("s32");
        s33.getAccessibleContext().setAccessibleName("s33");
        s34.getAccessibleContext().setAccessibleName("s34");
        s35.getAccessibleContext().setAccessibleName("s35");
        s36.getAccessibleContext().setAccessibleName("s36");
        s37.getAccessibleContext().setAccessibleName("s37");
        s38.getAccessibleContext().setAccessibleName("s38");
        s40.getAccessibleContext().setAccessibleName("s40");
        s41.getAccessibleContext().setAccessibleName("s41");
        s42.getAccessibleContext().setAccessibleName("s42");
        s43.getAccessibleContext().setAccessibleName("s43");
        s44.getAccessibleContext().setAccessibleName("s44");
        s45.getAccessibleContext().setAccessibleName("s45");
        s46.getAccessibleContext().setAccessibleName("s46");
        s47.getAccessibleContext().setAccessibleName("s47");
        s48.getAccessibleContext().setAccessibleName("s48");
        s50.getAccessibleContext().setAccessibleName("s50");
        s51.getAccessibleContext().setAccessibleName("s51");
        s52.getAccessibleContext().setAccessibleName("s52");
        s53.getAccessibleContext().setAccessibleName("s53");
        s54.getAccessibleContext().setAccessibleName("s54");
        s55.getAccessibleContext().setAccessibleName("s55");
        s56.getAccessibleContext().setAccessibleName("s56");
        s57.getAccessibleContext().setAccessibleName("s57");
        s58.getAccessibleContext().setAccessibleName("s58");
        s60.getAccessibleContext().setAccessibleName("s60");
        s61.getAccessibleContext().setAccessibleName("s61");
        s62.getAccessibleContext().setAccessibleName("s62");
        s63.getAccessibleContext().setAccessibleName("s63");
        s64.getAccessibleContext().setAccessibleName("s64");
        s65.getAccessibleContext().setAccessibleName("s65");
        s66.getAccessibleContext().setAccessibleName("s66");
        s67.getAccessibleContext().setAccessibleName("s67");
        s68.getAccessibleContext().setAccessibleName("s68");
        s70.getAccessibleContext().setAccessibleName("s70");
        s71.getAccessibleContext().setAccessibleName("s71");
        s72.getAccessibleContext().setAccessibleName("s72");
        s73.getAccessibleContext().setAccessibleName("s73");
        s74.getAccessibleContext().setAccessibleName("s74");
        s75.getAccessibleContext().setAccessibleName("s75");
        s76.getAccessibleContext().setAccessibleName("s76");
        s77.getAccessibleContext().setAccessibleName("s77");
        s78.getAccessibleContext().setAccessibleName("s78");
        s80.getAccessibleContext().setAccessibleName("s80");
        s81.getAccessibleContext().setAccessibleName("s81");
        s82.getAccessibleContext().setAccessibleName("s82");
        s83.getAccessibleContext().setAccessibleName("s83");
        s84.getAccessibleContext().setAccessibleName("s84");
        s85.getAccessibleContext().setAccessibleName("s85");
        s86.getAccessibleContext().setAccessibleName("s86");
        s87.getAccessibleContext().setAccessibleName("s87");
        s88.getAccessibleContext().setAccessibleName("s88");

        txtConsole.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtConsole.setForeground(new Color(255, 255, 255));
        txtConsole.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtConsole.setText("¡ Presione resolver para iniciar !");

        log.setEditable(false);
        log.setColumns(20);
        log.setRows(5);
        log.setFocusable(false);
        jScrollPane1.setViewportView(log);

        txt_console1.setBackground(new Color(51, 51, 51));
        txt_console1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_console1.setForeground(new Color(255, 255, 255));
        txt_console1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_console1.setText("Log");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(sudokuContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_console1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtConsole, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtConsole, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_console1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(sudokuContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton execute;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea log;
    public JLabel s00;
    public JLabel s01;
    public JLabel s02;
    public JLabel s03;
    public JLabel s04;
    public JLabel s05;
    public JLabel s06;
    public JLabel s07;
    public JLabel s08;
    public JLabel s10;
    public JLabel s11;
    public JLabel s12;
    public JLabel s13;
    public JLabel s14;
    public JLabel s15;
    public JLabel s16;
    public JLabel s17;
    public JLabel s18;
    public JLabel s20;
    public JLabel s21;
    public JLabel s22;
    public JLabel s23;
    public JLabel s24;
    public JLabel s25;
    public JLabel s26;
    public JLabel s27;
    public JLabel s28;
    public JLabel s30;
    public JLabel s31;
    public JLabel s32;
    public JLabel s33;
    public JLabel s34;
    public JLabel s35;
    public JLabel s36;
    public JLabel s37;
    public JLabel s38;
    public JLabel s40;
    public JLabel s41;
    public JLabel s42;
    public JLabel s43;
    public JLabel s44;
    public JLabel s45;
    public JLabel s46;
    public JLabel s47;
    public JLabel s48;
    public JLabel s50;
    public JLabel s51;
    public JLabel s52;
    public JLabel s53;
    public JLabel s54;
    public JLabel s55;
    public JLabel s56;
    public JLabel s57;
    public JLabel s58;
    public JLabel s60;
    public JLabel s61;
    public JLabel s62;
    public JLabel s63;
    public JLabel s64;
    public JLabel s65;
    public JLabel s66;
    public JLabel s67;
    public JLabel s68;
    public JLabel s70;
    public JLabel s71;
    public JLabel s72;
    public JLabel s73;
    public JLabel s74;
    public JLabel s75;
    public JLabel s76;
    public JLabel s77;
    public JLabel s78;
    public JLabel s80;
    public JLabel s81;
    public JLabel s82;
    public JLabel s83;
    public JLabel s84;
    public JLabel s85;
    public JLabel s86;
    public JLabel s87;
    public JLabel s88;
    public javax.swing.JPanel sudokuContainer;
    public JLabel txtConsole;
    private JLabel txt_console1;
    // End of variables declaration//GEN-END:variables
}
